### ISSUE TITLE
Fail Parsing

### ISSUE THREAD

**Issue by mghozyah** [aswansyahputra/bandungjuara#1]
Malam kang, kenapa pas saya import datanya keluar error seperti ini ya?

`smp <- cari(kata_kunci = "smp")`
`data_smp <- impor(.data = smp)`
`data_smp`

-----
1 parsing failure.
row col  expected    actual                                                                                                          file
 58  -- 7 columns 8 columns 'https://git.bandung.go.id/opendatabdg/databdg/raw/master/resources/f0f/4c8/data-rekap-prestasi-2014-smp.csv'
Missing column names filled in: 'X11' [11]Semua dataset berhasil diunduh!

**Comment by aswansyahputra** [comment]
Selamat siang mas,

Oh itu hanya *warning* mas, bukan *error*. Jadi sebenarnya itu datanya sudah berhasil diimpor, namun ada penambahan satu kolom `X11` secara otomatis pada salah satu dataset.

Di versi terbaru yang baru saya *pushed*, *warning* tersebut sudah dibisukan dan penambahan kolom secara otomatis tersebut telah diperbaiki. Silakan mas bisa update ke `bandungjuara` versi 0.1.2.
